version: "2.2"
services:
  db:
    image: postgres:12
    container_name: communa_db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=db_password
    restart: unless-stopped

  webapp:
    build: .
    container_name: communa_web
    expose:
      - 8000
    ports:
      - 8000:8000
    restart: unless-stopped
    depends_on:
      - db
    links:
      - db